config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  root 'pages#home'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname, :captcha => true

  # Declare the email headers. It accepts anything the mail method
  #in ActionMailer accepts

  def headers
    {
        :subject => "Requesting Info from #{name}",
        :to      => "jsaintvi@kent.edu",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact =Contact.new(params[:contact])
    @contact.request = request

    if @contact.deliver
      flash.now[:notice] = "Thank you for your message. We will contact you soon!"
    else
      flash.now[:error] = "Cannot send message."
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_new_form.html.erb
  <form id="part6">
    <h3 align="center" style="color: #ef4056; font-size: larger; font-weight: bolder; margin-top: 2%">Send Me a Message for More Info</h3>

    <%= simple_form_for Contact.new, :html => {class: "form-horizontal"} do |f| %>
        <div class="form-group">
          <label for="exampleInputEmail1" style="color: blue; font-weight: bolder">Your Name</label>
          <%= f.text_field :name, :required => true, label: false, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1" style="color: blue; font-weight: bolder">Email address</label>
          <%= f.text_field :email, :required => true, label: false, class:"form-control" %>
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1" style="color: blue; font-weight: bolder">Message</label>
          <%= f.text_field :message, :as => :text, :required => true, label: false, class:"form-control" %>

          <div class="hidden">
            <%= f.input :nickname, :hint => "Leave this field blank!" %>
          </div>
        </div>


        <div style="margin-left: 20%; margin-bottom: 20px;">
          </br>
          <%= f.button :submit, "Send message", :class => "btn btn-primary" %>
        </div>


    <% end %>

  </form>


<!--
<div class="container">
  <h3>Send Me a Message for More Info</h3>
  <form>
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-group">
      <label for="exampleInputFile">File input</label>
      <input type="file" id="exampleInputFile">
      <p class="help-block">Example block-level help text here.</p>
    </div>
    <div class="checkbox">
      <label>
        <input type="checkbox"> Check me out
      </label>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>

-->

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
  <div>
    <a href="#" data-dismiss="alert">x</a>
    <%= value %>
  </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="container">
<%= render "contacts/new_form"  %>

</div>

<!--
<div class="container">
  <h3>Send Me a Message for More Info</h3>
  <form>
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-group">
      <label for="exampleInputFile">File input</label>
      <input type="file" id="exampleInputFile">
      <p class="help-block">Example block-level help text here.</p>
    </div>
    <div class="checkbox">
      <label>
        <input type="checkbox"> Check me out
      </label>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>

-->

app/views/layouts/_footer.html.erb
<!--

            Work form Bootsnipp

-->
<!--
<div id="footer">
  <div class="container">
    <div class="row">

      <br>
      <div class="col-md-4">
        <center>
          <img src="http://oi60.tinypic.com/w8lycl.jpg" class="img-circle" alt="the-brains">
          <br>
          <h4 class="footertext">Programmer</h4>
          <p class="footertext">You can thank all the crazy programming here to this guy.<br>
        </center>
      </div>
      <div class="col-md-4">
        <center>
          <img src="http://oi60.tinypic.com/2z7enpc.jpg" class="img-circle" alt="...">
          <br>
          <h4 class="footertext">Artist</h4>
          <p class="footertext">All the images here are hand drawn by this man.<br>
        </center>
      </div>
      <div class="col-md-4">
        <center>
          <img src="http://oi61.tinypic.com/307n6ux.jpg" class="img-circle" alt="...">
          <br>
          <h4 class="footertext">Designer</h4>
          <p class="footertext">This pretty site and the copy it holds are all thanks to this guy.<br>
        </center>
      </div>
    </div>
    <div class="row">
      <p><center><a href="#"></a> <p class="footertext">Copyright 2015</p></center></p>
    </div>
  </div>
</div>

-->


<div class="row">
    <footer id="footerFormat">
      <div class="footer" id="footer">

          <div class="container">
            <div class="row">
              <div class="footer-title">Contact us</div>
              <div class="footer-subtitle"></div>
            </div>
            <div class="row">
              <div class="footer-column">

                <div class="info-box contact-form-success" id="contact-form-success" style="display:none;"></div>
                <div class="info-box contact-form-errors" id="contact-form-errors"></div>
                <!--
                <form accept-charset="UTF-8" action="/deliver_mail" data-remote="true" id="contact_form" method="post"><div style="display:none"><input name="utf8" type="hidden" value="✓"></div>
                  <div class="form-group">
                    <div class="form-controls">
                      <input id="name" name="name" placeholder="name" type="text" value="">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="form-controls">
                      <input id="email" name="email" placeholder="email" type="text" value="">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="form-controls">
                      <textarea id="message" name="message" placeholder="message"></textarea>
                    </div>
                  </div>
                  <div class="form-group submit-button">
                    <input name="commit" type="submit" value="send">
                  </div>
                </form>
                 -->

                    <%= render "contacts/new_form" %>

                <div class="vr">&nbsp;</div>

                <div data-width="100%" class="fb-like-box" data-href="#" data-colorscheme="dark" data-show-faces="true" data-header="false" data-stream="false" data-show-border="true"></div>
              </div>
              <div class="footer-column" >

                <div class="half-width pull-left" style="color: white;">
                  <div class="footer-small-title" style="color: #ef4056; font-size: large; font-weight: bolder; margin-top: 2%">Contact:</div>
                  <div class="footer-content">
                    <a href="mailto:jsaintvi@kent.edu">jsaintvi@kent.edu</a>
                    <br>
                    phone: (330)289-7787
                  </div>
                </div>



    <br /> <br /> <br />

                <div class="half-width pull-left">
                  <div class="footer-small-title" style="color: #ef4056; font-size: large; font-weight: bolder; margin-top: 2%">Location :</div>
                  <div class="footer-content">
                    Jodex Saint-Vil
                    <br>
                    225 Midway Drive
                    <br>
                    Kent, Ohio

                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>


      <div class="black-footer">
        <div class="container">
          <div class="footer-copyright">
            © 2015 Jodex Saint-Vil - Ruby on Rails Developer | Software Developer
            &nbsp;
          </div>
        </div>
      </div>

    </footer>

</div>

app/views/layouts/_header.html.erb
<div class="row">
      <div class="dark site-region" data-menu-item="#part1Btn" id="part1" style="height: 566px; background-position: 50% -197px;">

        <div class="navbar " id="top_navbar" style="display: block;">
          <div class="navbar-wrapper ">
            <div class="left-nav">
              <a class="logo-regular" href="#"><img alt="Logo" src="/assets/logo1.png" title="email me" class="imgManipulation im1"></a> <!-- thnkinh about linking ti to contacting me -->
              <a class="logo-fixed" href="#part1"><img alt="Logo nav" src="/assets/jodex.jpg" class="imgManipulation im2"></a> <!-- link to home page -->
            </div>

            <div class="nav-collapse ">
              <span class="movingUnderlay" style="left: 9px; width: 55px;"></span>
              <ul class="nav navbar-nav navbar-right headerFormat ">
                <li><%= link_to "Home", root_path, class: "listHeader spaceRight" %></li>
                <li><%= link_to "About Me", "#part2", class: "listHeader spaceRight" %></li>
                <li><%= link_to "What i Do", "#part3", class: "listHeader spaceRight" %></li>
                <li><%= link_to "Projects", "#part4", class: "listHeader spaceRight" %></li>
                <li><%= link_to "WorkLanguages", "#part5", class: "listHeader spaceRight" %></li>
                <li><%= link_to "Contact Me",contacts_path,  class: "listHeader spaceRight" %></li>
              </ul>
              <!--
              <div class="navbar-item"><a href="#part1" id="HomeBtn">Home</a></div>
              <div class="navbar-item"><a href="#part2" id="AboutusBtn">About us</a></div>
              <div class="navbar-item"><a href="#part3" id="PortfolioBtn">Portfolio</a></div>
              <div class="navbar-item"><a href="#part5" id="ProjectsBtn">Projects</a></div>
              <div class="navbar-item"><a href="#part8" id="TeamBtn">Team</a></div>
              <div class="navbar-item" data-label="Work"><a href="https://binarapps.com/praca">Work</a></div>
              <div class="navbar-item" data-label="Blog"><a href="https://binarapps.com/blog/">Blog</a></div>
              <div class="navbar-item"><a href="#footerInner" id="ContactBtn">Contact</a></div>
              -->
            </div>
            <div class="container no-top-margin">
              <div class="heading">
                <div class="head-row">I Am</div>
                <div class="head-row">
                  <span class="pink-font" style="margin-left: 10%" > A SOFTWARE / WEB DEVELOPER</span>
                </div>
              </div>
              <div class="intro">
                <div class="intro-row">I am passionate about Ruby on Rails and new web</div>
                <div class="intro-row">technologies. </div>
              </div>
              <div class="btn btn-info start" style="background-color: #ccc">
                <div class="get-str-btn" style="margin-bottom: 5%;"><a class="btn button1" href="#part2" id="getStartedBtn" style="color: black">get started</a></div>
                <div class="arrow-down"><a href="#part2" id="dotsBtn"><img alt="Arrow down" src="/assets/arrow-down.png"></a></div>
              </div>
            </div>
          </div>
        </div>
      </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jodex-website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">

<div class="p_header">
  <%= render "layouts/header" %>
</div>
<div class="p_header">
  <%= yield %>
</div>

<div class="footerStyling">
  <%= render "layouts/footer" %>
</div>

</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="light site-region" id="part2">

        <div class="container">
          <div class="title first big-top-margin">
            About Me
            <span class="pink-font">(Jodex Saint-Vil)</span>
          </div>
          <div class="subtitle">
            Doing the best to get project done on time. I work hard till i meet the deadline
            <em> of every</em>
            challenge.
          </div>
        </div>

        <!-- EXPETIMRNTING WITH TIMELINE PANEL FOR INFO ANOUT ME DISPLAY-->
        <div class="row">

        <div class="row" style="margin-left: 2%; margin-right: 2%; margin-top: 5%;">
        <div class="row colorFormatting">
          <div class="col-lg-12">
                <ul class="timeline">
                  <li>
                        <div class="timeline-image">
                          <img class="img-circle img-responsive" src="/assets/jodex.jpg" alt="Jodex's pic">
                        </div>
                        <div class="timeline-panel">
                              <div class="timeline-heading">
                                <h4 style="color: red">Info About Me</h4>
                                <h4 class="subheading">Jodex S.</h4>
                              </div>
                              <div class="timeline-body" style="margin-left: 15%;">
                                <p class="text-muted" style="font-size: large; color: white">
                                    Graduated from Kent State University in Fall 2015. I am currently studying computer science and minoring in math. I am a Software/Web developer and  I love writing software programs tho sometimes it means replicating someone else's work. I am a Ruby On Rails lover.
                                </p>
                              </div>
                        </div>
                        <div class="line"></div>
                  </li>

                  <li class="timeline-inverted">
                        <div class="timeline-image">
                          <img class="img-circle img-responsive" src="/assets/hireme.jpg" alt="Hire Me">
                        </div>
                        <div class="timeline-panel">
                              <div class="timeline-heading">
                                <h4 style="color: red">Why you should hire me?</h4>
                                <!--<h4 class="subheading">Hire </h4>-->
                              </div>
                              <div class="timeline-body" style="margin-right: 15%">
                                <p class="text-muted" style="font-size: large;">
                                    Guarantee to give you a great service and test the projects through and throu making sure you get the best quality software and minimizing errors as best as possible. Overall, you will love me and the way I approach
                                </p>
                              </div>
                        </div>
                        <div class="line"></div>
                  </li>

                  <li>
                        <div class="timeline-image">
                          <img class="img-circle img-responsive" src="/assets/report.jpg" alt="Reports">
                        </div>
                        <div class="timeline-panel">
                              <div class="timeline-heading">
                                <h4 style="color: red">Report Very Often</h4>
                              </div>
                              <div class="timeline-body" style="margin-left: 15%">
                                <p class="text-muted" style="font-size: large">
                                    Very detailed reports on the progress made on the project (and source code if you so choose to look at it)
                                </p>
                              </div>
                        </div>

                  </li>


                </ul>
            </div>
        </div>
    </div>
  </div>
        <!--  end of timeline (from bootsnipp)  -->

        <hr style="border: 0;height: 1px;background: #333;background-image: linear-gradient(to right, #ccc, #333, #ccc); margin-top: -2%;" />


      </div>

<!-- start of work section -->
      <div class="container" id="part3">

        <div class="dark">
          <div class="arrow-down-grey arrow-2"><a href="#part6" id="part6Btn"><img alt="Arrow down grey" style="margin-left: 45%;" src="/assets/arrow-down.png"></a></div>
          <div class="banner" style="background-position: 50% -129px;">
            <div class="container">
              <div class="subheading">
                <div class="subhead row" style="margin-left: 45%; margin-top: 2%;font-size: large">
                  WHAT I
                  <span class="pink-font">DO?</span>
                </div>
              </div>
              <div class="subcontent">
                <p style="font-size: 22px; color: black; text-align: center">
                   I create and develop software | web applications in Ruby on Rails.
                  <br /><br />
                   Check some of <%= link_to "my projects", "#part4", class: "btn pink-font projects " %> in projects folder
                </p>
              </div>
              <div class="start" style="margin-right: -20%;">
                <div class="bcm-cnt-btn"><%= link_to "contact me", contacts_path, class: "btn pink-font contactMe"  %>
                  <!--<a class="btn" href="#footerInner" id="contactUsBtn">contact me</a> -->
                </div>
              </div>
            </div>
          </div>
        </div>


        </div>
<hr style="border: 0;height: 1px;background: #333;background-image: linear-gradient(to right, #ccc, #333, #ccc);" />

   <!-- end  of s=work section -->
<!--
    projects section, listing the projects i have worked on
-->
<div class="container" id="part4">
  <h3 class="btn pink-font projectsFormat bcm-cnt-btn" style="text-align: center; font-size: larger; color: #ef4056; margin-left: 35%">Projects with a big meaning to me( to list a few)</h3>
  <p style="margin-left: 24%; font-size: medium; margin-bottom: 2%; margin-top: 1%; font-weight: bold">Those are the projects i worked on at the very beginning of my journey in developing</p>

  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="/assets/math_a_magic.jpg" alt="Math-A-Magic Project">
        <div class="caption">
          <h3 style="text-align: center;font-weight: bolder; font-size: large; font-style: oblique; color: #ef4056; ">Math-A-Magic</h3>
          <p>Developed a Calculus solving program for college students. It is a more user-friendly program for students who have no experience with Wolfram Alpha and other high-end Math software packages.<i style="color: #00008b">(Worked with Emil Shirima, Chang)</i> </p>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="/assets/math_a_magic.jpg"  alt="J-Flex  Trade(the trading robot)" />
        <div class="caption">
          <h3 style="text-align: center;font-weight: bolder; font-size: large; font-style: oblique; color: #ef4056">J-Flex Trade</h3>
          <p>Building a trading robot that takes into account trading.The aim was for me to build a <u>PROFITABLE</u> robot. Hoping to be able to apply it to bitcoins and be able to make lots of $$$ on trading in the near future <i style="color: #00008b"> (who am I kidding?! in the coming 2-3 years</i></p>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="/assets/math_a_magic.jpg"  alt="Recipe App">
        <div class="caption">
          <h3 style="text-align: center;font-weight: bolder; font-size: large; font-style: oblique; color: #ef4056">Food recipe App</h3>
          <p>Wrote an iphone that displays list of recipes, along with videos and provide the ability to share with each other, and also compete to see who was more creative on a mothly basis based on votes <i style="color: #00008b">(which comes from friends of users only)</i></p>
        </div>
      </div>
    </div>

  </div>

  <!-- end of projects section -->

<!-- languages used for projects -->
<hr style="border: 0;height: 1px;background: #333;background-image: linear-gradient(to right, #ccc, #333, #ccc);" />
    <div class="row" id="part5">
            <div class="row title">
              <span class="pink-font">Languages/Framework I use</span>
            </div>
            <div class="row" id="imgBackground">
              <p style="color: black;font-size: large; text-align: center; font-weight: normal; font-family: sans-serif; font-variant: historical-forms;">
                To provide you with great service and make you happy, i use the following languages/frameworks to work with:&nbsp;
                <br> <br>
              </p>
              <div class="languageImagesStyling" style="margin-left: 5px;margin-right: -4%;">
                    <img alt="Ruby/Ruby on Rails, JavaScript" src="/assets/rails.jpg" style="max-width:100%;">
                    <img alt="html" src="/assets/html.png" style="max-width:100%;">
                    <img alt="css" src="/assets/css.jpg" style="max-width:100%;">
                    <img alt="jQuery" src="/assets/jquery.png" style="max-width:100%;">


                    <img alt="MySql" src="/assets/mysql.jpg" style="max-width:100%;">
                    <img alt="PHP" src="/assets/php.jpg" style="max-width:100%;">
                    <img alt="C_Sharp" src="/assets/c_sharp.jpg" style="max-width:100%;">
                    <img alt="CPlusPlus" src="/assets/cplusplus.png" style="max-width:100%;">
                </div>
              </div>
            </div>

          </div>
      </div>
    </div>

<hr style="border: 0;height: 1px;background: #333;background-image: linear-gradient(to right, #ccc, #333, #ccc);" />





</div>